### ISSUE TITLE
CGA files are missing

### ISSUE THREAD

**Issue by sxsong1207** [timqqt/Synthinel#1]
Dear authors,

Thanks for your great work. While I am viewing your code, I found that the CGA rules that you used to label the building are missing. Would you mind sharing them?

Thank you,
Shaun

**Comment by timqqt** [comment]
Hi Shaun,

No problems. But I did check that the CGA rule for labelling are included in the folder "./bin". You can get the labels of a synthetic city by rendering its corresponding labelling CGA rules again.

Best,
Fanjie


***********************************

Fanjie Kong

Ph.D. Student in Machine Learning

Electrical and Computer Engineering Department

Duke University

Durham, NC, 27708

Email: ***@***.***

LinkedIn: https://www.linkedin.com/in/fanjie-kong-9330a6196/

***********************************

________________________________
From: Shaun Song ***@***.***>
Sent: Thursday, May 27, 2021 12:09
To: timqqt/Synthinel ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [timqqt/Synthinel] CGA files are missing (#1)


Dear authors,

Thanks for your great work. While I am viewing your code, I found that the CGA rules that you used to label the building are missing. Would you mind sharing them?

Thank you,
Shaun

**Comment by sxsong1207** [comment]
Hi Fanjie,

Thanks for your reply, yeah, I found those CGA rules as well, but they look like been compiled into binary format. I hope to study with your source code if you can release them.

Thank you,
Shaun

**Comment by timqqt** [comment]
> Hi Fanjie,
> 
> Thanks for your reply, yeah, I found those CGA rules as well, but they look like been compiled into binary format. I hope to study with your source code if you can release them.
> 
> Thank you,
> Shaun

Yes. Definitely. Please use ./scripts/one_shot_9_cities/one_shot_9_cities_test.py to create synthetic tiles. I used a python program to convert them into binary format via thresholding. I will update this later.

**Comment by timqqt** [comment]
> Hi Fanjie,
> 
> Thanks for your reply, yeah, I found those CGA rules as well, but they look like been compiled into binary format. I hope to study with your source code if you can release them.
> 
> Thank you,
> Shaun

Hi, 

Here's my source code. I will update a more formal version of this pre-processing part.

import glob, os
import cv2
import numpy as np
import scipy.misc as smc
import numpy as np
import re
import matplotlib.pyplot as plt
from scipy.signal import convolve2d
from skimage.transform import resize
# truncate to square and then resize
final_res = ()
file_name_list = []
file_path = ''
filename2 = os.listdir('./')




def num_2_str(num):
    num_list = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26']
    c_list = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
    num2c = dict(zip(num_list, c_list))
    return ''.join([num2c[e_n] for e_n in num])


for file in glob.glob(file_path + "*RGB.jpg"):
    num = re.findall(r"\d+\.?\d*", file.replace(file_path, ''))
    if 'random_city_s' + '_' + num_2_str(num[0]) + '_' + num[1] + '_RGB.tif' in filename2:
        continue
    if '_random_city_1' in file.replace(file_path, ''):
        continue
    if '_random_city_2' in file.replace(file_path, ''):
        continue
    if '_random_city_3' in file.replace(file_path, ''):
        continue
    if '_random_city_4' in file.replace(file_path, ''):
        continue
    if '_random_city_5' in file.replace(file_path, ''):
        continue
    if '_random_city_6' in file.replace(file_path, ''):
        continue
    img = smc.imread(file)
    img_gt = smc.imread(file.replace('RGB', 'GT'))
    t_shape = min(img.shape[0], img.shape[1])
    img_GT = np.zeros((t_shape, t_shape))
    img_RGB = np.zeros((t_shape, t_shape, img.shape[2]))
    file = file.replace(file_path, '')
    num = re.findall(r"\d+\.?\d*", file)
    print("-"*10+'Now processing '+ file +'-'*10)
    img = img[:t_shape, :t_shape, :]
    img_gt = img_gt[:t_shape, :t_shape, :]

    img_diff = img - img_gt
    # plt.imshow(img_diff)
    # plt.show()
    for i in range(t_shape):
        for j in range(t_shape):
            #img_GT[i, j] = 255 if ((img_diff[i, j, 0] + img_diff[i, j, 1] + img_diff[i, j, 2] > 3) and (img_diff[i, j, 0] < 251) and (img_diff[i, j, 1]<251) and (img_diff[i, j, 2]<251))else 0
            img_GT[i, j] = 255 if (img_gt[i, j, 0],img_gt[i, j, 1],img_gt[i, j, 2]) < (10,10,10) else 0
    img_GT = cv2.morphologyEx(img_GT, cv2.MORPH_OPEN, np.ones((5,5)))
    img_GT = cv2.morphologyEx(img_GT, cv2.MORPH_CLOSE, np.ones((2,2)))

    img_GT = smc.imresize(img_GT, final_res, interp='nearest')

    img_RGB = img[:t_shape, :t_shape, :]
    img_RGB = resize(img_RGB, final_res, anti_aliasing=True)

    build_detector = np.sum(img_GT)
    if build_detector < 255000:
        print('No building in this patch!')
        continue
    else:
        smc.imsave('random_city_s' + '_' + num_2_str(num[0]) + '_' + num[1] + '_RGB.tif'
                   , img_RGB)
        smc.imsave('random_city_s'+'_'+num_2_str(num[0])+'_'+num[1] + '_GT.tif'
                   , img_GT)
    file_name_list.append('random_city_s' + '_' + num_2_str(num[0]) + '_' + num[1])

# save as file for collection
print(file_name_list)
np.savetxt('colTileNames.txt', np.array(file_name_list), fmt='%s', delimiter='\n')
