### ISSUE TITLE
GT are just completely black .tif files

### ISSUE THREAD

**Issue by tdchua** [timqqt/Synthinel#2]
Hello, I was wondering if there was a problem with the ground truth .tif files? 
They appear completely black in my window

![Screen Shot 2021-12-22 at 9 30 47 PM](https://user-images.githubusercontent.com/23580577/147093131-e929f9de-8931-4931-9ba6-e6f1f9f2b69b.png)

**Comment by timqqt** [comment]
I think I normalized the GT to [0,1] before I upload it to Google Drive, so it will not show up properly. Please download them and you will see the groundtruth.
